spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/testdb
    username: postgres
    password: admin@123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update